### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by giabos** [Alfresco/generator-ng2-alfresco-app#12]
Hi,
I have a problem when trying to log into the generated ng2 application (all options selected).

First, I'm receiving the error 401 (Unauthorized). Here is the request in error:

> POST /alfresco/api/-default-/public/authentication/versions/1/tickets HTTP/1.1
> Host: localhost:8080
> Connection: keep-alive
> Content-Length: 37
> Accept: application/json
> Origin: http://localhost:3000
> Authorization: Basic Uk9MRV9USUNLRVQ6
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
> Content-Type: application/json
> Referer: http://localhost:3000/
> Accept-Encoding: gzip, deflate
> Accept-Language: en,fr;q=0.8,en-US;q=0.6,nl;q=0.4,de;q=0.2

When looking into it, it seems that the Authorization header is wrong, as my login is **admin:admin**, the base64 string should be: **YWRtaW46YWRtaW4=**

I tried then to make the post manually after changing the Authorization header and then I have another error:

> POST /alfresco/api/-default-/public/authentication/versions/1/tickets HTTP/1.1
> Host: localhost:8080
> Authorization: Basic YWRtaW46YWRtaW4=
> Content-Type: application/json
> Cache-Control: no-cache
> Postman-Token: b7119428-7d2d-f3c3-2259-eb06b8073626
> 
> {"userId":"admin","password":"admin"}

Response:
> {
>   "error": {
>     "errorKey": "framework.exception.InvalidApiArgument",
>     "statusCode": 400,
>     "briefSummary": "06130002 framework.exception.InvalidApiArgument",
>     "stackTrace": "[org.alfresco.rest.framework.core.ResourceLookupDictionary.locateRelationResource(ResourceLookupDictionary.java:47), org.alfresco.rest.framework.core.ResourceLookupDictionary.locateEntityResource(ResourceLookupDictionary.java:33), org.alfresco.rest.framework.core.ResourceLookupDictionary.locateResource(ResourceLookupDictionary.java:97), org...

It seems that the authorization Rest API is not available in my alfresco installation (Community Edition V 5.1.g on Centos 6.5).

Can you check what could be wrong ?
Also, let me know if you need more details.

Thanks!
Giovanni.

**Comment by ohej** [comment]
Hi Giovanni

You need Alfresco 5.2.a which is in the Alfresco Community 201606-EA release to have the APIs required. Please read https://www.alfresco.com/blogs/developer/2016/06/30/announcing-alfresco-ng2-components/ and https://github.com/Alfresco/alfresco-ng2-components/blob/master/PREREQUISITES.md for more information. 

/Ole

**Comment by giabos** [comment]
Hi Ole,
Ok, clear, thanks!
I've read the 2nd link and it was not clear that V5.2a was required.
First link you proposed makes it more clear.

Giovanni.
