### ISSUE TITLE
BrowserModuleAnimation should be imported

### ISSUE THREAD

**Issue by witchedwiz** [Alfresco/generator-ng2-alfresco-app#127]
as per issue subject..
during any transition even with the stock application you'll receive an error in the console complainign about missing browser animation modules..
effectively it's right..
the template app should be corrected adding the following content in the app.module.ts

import { BrowserAnimationsModule } from '@angular/platform-browser/animations';

@NgModule({
  imports: [
    .....
    // missing animation modules
    BrowserAnimationsModule,
    .....
  ],

You can easily replicate it with the app after doing an npm start after running the generator.

**Comment by eromano** [comment]
thanks @witchedwiz this issue has been already solved in development https://github.com/Alfresco/generator-ng2-alfresco-app/blob/development/app/templates/adf-cli-acs-aps-template/src/app/app.module.ts it will be release with the version 2.3.0
