### ISSUE TITLE
Generated app searching for Login. Registration not available though

### ISSUE THREAD

**Issue by durdevic** [Alfresco/generator-ng2-alfresco-app#178]
So I generated the app with `yo alfresco-adf-app` and now I can't see anything because it searches for login, and when I click on register, he just redirects me to the front page. 

Solution please?

**Comment by eromano** [comment]
Hi @durdevic which template did you generated?
did you change the app.config.json to point your environment?

**Comment by durdevic** [comment]
Yup, figured it out in the mean time, build a docker image and pointed it to it, as you already proposed. 

Thanks @eromano 👌
