### ISSUE TITLE
Fail to install generator.

### ISSUE THREAD

**Issue by silverskyvicto** [Alfresco/generator-ng2-alfresco-app#206]
Hi.

I tried to install generator-ng2-alfresco-app. but I faced to error below.

### Environment
|tool        |version  |
|:--------|:--------|
|Node.js | v10.15.3
|yeoman | 2.0.6     |

### Error
```
$ npm install -g generator-alfresco-adf-app
npm WARN checkPermissions Missing write access to /Users/ey/.nodebrew/node/v10.15.3/lib/node_modules/generator-alfresco-adf-app
npm ERR! path /Users/ey/.nodebrew/node/v10.15.3/lib/node_modules/generator-alfresco-adf-app
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall access
npm ERR! enoent ENOENT: no such file or directory, access '/Users/ey/.nodebrew/node/v10.15.3/lib/node_modules/generator-alfresco-adf-app'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ey/.npm/_logs/2019-05-25T10_43_18_823Z-debug.log
```

**Comment by eromano** [comment]
Hi it looks like you OS problem in access to that folder

**Comment by silverskyvicto** [comment]
After upgrading Node.js to v10.16.0, I was able to install the generator.

It's strange that you can install it or not with just a slightly different version, but once you have achieved your goal for the time being, it's okay to close it.
