### ISSUE TITLE
Compatibility issue with newest angular-cli

### ISSUE THREAD

**Issue by ycoulon** [Alfresco/generator-ng2-alfresco-app#24]
Hi,

When trying to generate a new components using angular-cli got the following error : 
```
It seems like you're using a project generated using an old version of the Angular CLI.
The latest CLI now uses webpack and includes a lot of improvements, include a simpler
workflow, a faster build and smaller bundles.

To get more info, including a step-by-step guide to upgrade the CLI, follow this link:
https://github.com/angular/angular-cli/wiki/Upgrading-from-Beta.10-to-Beta.14
```

**Comment by DenisVuyka** [comment]
Yeoman and angular-cli are completely different and incompatible at this point generators. Angular-cli helps you creating **blank** project that works by angular-cli rules (all commands and configs are wired with the expectations of the structure they generate from the blueprint). Yeoman generator from the other side provides you with a scaffold that is preconfigured with ADF components. 

angular-cli is still in beta and does not support custom blueprints (to be able wiring ADF setup with it). Even if we upgrade ADF demo shell to use angular-cli it does not make any sense wrapping generated result into yet another (yeoman) generator as we will be bound to updating it every time angular-cli team makes a commit.

**Comment by ycoulon** [comment]
Ok thanks for the answer.
