### ISSUE TITLE
"npm install -g generator-ng2-alfresco-app" fails on Windows 7 & CentOS 7.2

### ISSUE THREAD

**Issue by sujaypillai** [Alfresco/generator-ng2-alfresco-app#3]
Trying to execute the command - "npm install -g generator-ng2-alfresco-app" fails on Windows 7 & CentOS 7.2

Attaching the npm-debug.log for both environment.

[npm-debug-centos.txt](https://github.com/Alfresco/generator-ng2-alfresco-app/files/340724/npm-debug-centos.txt)
[npm-debug-win7.txt](https://github.com/Alfresco/generator-ng2-alfresco-app/files/340723/npm-debug-win7.txt)

**Comment by magemello** [comment]
Hi Sujay,

Thanks for your feedback. Can you clone the project from Github and then try to execute the following commands inside the generator folder:

```
$ npm install -g nsp
$ nsp check
```

I think this thing could help us to understand the problem.

**Comment by sujaypillai** [comment]
Hi Mario,

Here is the output for Win7.

C:\alf51dev\angular\generator-ng2-alfresco-app>npm install -g nsp
C:\Users\pillais1\AppData\Roaming\npm\nsp -> C:\Users\pillais1\AppData\Roaming\npm\node_modules\nsp\bin\nsp
C:\Users\pillais1\AppData\Roaming\npm
`-- nsp@2.5.0
  +-- chalk@1.1.3
  | +-- ansi-styles@2.2.1
  | +-- escape-string-regexp@1.0.5
  | +-- has-ansi@2.0.0
  | | `-- ansi-regex@2.0.0
  | +-- strip-ansi@3.0.1
  | | `-- ansi-regex@2.0.0
  | `-- supports-color@2.0.0
  +-- cli-table@0.3.1
  | `-- colors@1.0.3
  +-- https-proxy-agent@1.0.0
  | +-- agent-base@2.0.1
  | | `-- semver@5.0.3
  | +-- debug@2.2.0
  | | `-- ms@0.7.1
  | `-- extend@3.0.0
  +-- joi@6.10.1
  | +-- hoek@2.16.3
  | +-- isemail@1.2.0
  | +-- moment@2.12.0
  | `-- topo@1.1.0
  +-- nodesecurity-npm-utils@5.0.0
  +-- path-is-absolute@1.0.0
  +-- rc@1.1.6
  | +-- deep-extend@0.4.1
  | +-- ini@1.3.4
  | +-- minimist@1.2.0
  | `-- strip-json-comments@1.0.4
  +-- semver@5.1.0
  +-- subcommand@2.0.3
  | +-- cliclopts@1.1.1
  | +-- debug@2.2.0
  | | `-- ms@0.7.1
  | +-- minimist@1.2.0
  | `-- xtend@4.0.1
  `-- wreck@6.3.0
    +-- boom@2.10.1
    `-- hoek@2.16.3


C:\alf51dev\angular\generator-ng2-alfresco-app>nsp check
(+) No known vulnerabilities found

**Comment by eromano** [comment]
@sujaypillai can you update the generator version to 0.0.18 and retry?

**Comment by sujaypillai** [comment]
Got success on Win7 -

> C:\alf51dev\angular\generator-ng2-alfresco-app>npm generator --version
3.10.2

> C:\alf51dev\angular\generator-ng2-alfresco-app>npm install -g generator-ng2-alfresco-app
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
C:\Users\pillais1\AppData\Roaming\npm
`-- generator-ng2-alfresco-app@0.0.18

>

**Comment by eromano** [comment]
@sujaypillai great! can you check it also on CentOS 7.2?

**Comment by DenisVuyka** [comment]
Testing the same with the official **IE 11 on Win7** image without any problems. Used both admin and non-admin user. Used node.js 6.2.2 with npm 3.9.5

**Comment by ohej** [comment]
Tested with Mac OS X, Ubuntu and Win8, success all around for me

**Comment by sujaypillai** [comment]
Works with CentOS 7.2 with some warnings as below -

> npm WARN unmet dependency /lib/node_modules/block-stream requires inherits@'~2.0.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /lib/node_modules/fstream requires inherits@'~2.0.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /lib/node_modules/fstream-ignore requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /lib/node_modules/fstream-npm requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /lib/node_modules/glob requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /lib/node_modules/npmconf requires inherits@'~2.0.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /lib/node_modules/tar requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
generator-ng2-alfresco-app@0.0.19 /lib/node_modules/generator-ng2-alfresco-app
├── mkdirp@0.5.1 (minimist@0.0.8)
├── generator-license@3.1.1 (object-assign@4.1.0, process@0.11.5, git-config@0.0.7)
├── alfresco-logo@1.0.1 (strip-ansi@3.0.1, chalk@1.1.3, taketalk@1.0.0)
├── github-username@2.1.0 (gh-got@2.4.0, meow@3.7.0)
├── lodash@4.13.1
└── yeoman-generator@0.22.6 (yeoman-welcome@1.0.1, read-chunk@1.0.1, path-is-absolute@1.0.0, detect-conflict@1.0.0, yeoman-assert@2.2.1, class-extend@0.1.2, user-home@2.0.0, text-table@0.2.0, dargs@4.1.0, xdg-basedir@2.0.0, istextorbinary@1.0.2, path-exists@2.1.0, nopt@3.0.6, find-up@1.1.2, debug@2.2.0, async@1.5.2, error@7.0.2, chalk@1.1.3, shelljs@0.5.3, run-async@2.2.0, cli-table@0.3.1, glob@6.0.4, rimraf@2.5.2, mem-fs-editor@2.2.1, pretty-bytes@2.0.1, through2@2.0.1, underscore.string@3.3.4, inquirer@0.11.4, read-pkg-up@1.0.1, dateformat@1.0.12, html-wiring@1.2.0, download@4.4.3, lodash@3.10.1, cross-spawn@2.2.3, gruntfile-editor@1.2.0, yeoman-environment@1.6.1, yeoman-test@1.4.0)

**Comment by eromano** [comment]
Great! At this point I think we can close it. Thanks @sujaypillai @ohej  @DenisVuyka @magemello for the help
