### ISSUE TITLE
Readme.md - bad installation/startup instructions

### ISSUE THREAD

**Issue by stevenokennedy** [Alfresco/generator-ng2-alfresco-app#4]
The project's main readme.md file is out of date and gives instructions that don't seem to work with the current version of code.

> To test your project
> 
> $ npm run test
> To build the distribution files before releasing a new version.
> 
> $ npm run build
> To provide a live demo
> 
> $ npm run deploy

However, there don't seem to be any scripts in the package.json that match these names and all 3 commands fail.  As far as I can see I would need to run
`$npm run serve` or
`$npm run start` 

to actually run a live demo

**Comment by eromano** [comment]
HI @stevenokennedy,

Thanks, I will address this thing.
I  want to add a further explanation on this thing. There are two differents set of command:

1. The first set of command are for the Generator itself and you can find it in the main readme. The commands present in the main readme are for the people that want contribute to the generator. The only command that you can run is  the npm run test. So I am going to delete the others two

2. The second set of command are for the Generated project and you can find in the generated readme. These commands seem to be right and they are 

     - Install dependencies.
       npm install 
 
    - Fast build and watch for dev purposes.
       npm start
 
I think I can improve this explanation in the main readme of these two different set of commands.

**Comment by stevenokennedy** [comment]
Thanks, a lot clearer now
