### ISSUE TITLE
Creating App using non-default configuration results in invalid application

### ISSUE THREAD

**Issue by steve-codes** [Alfresco/generator-ng2-alfresco-app#41]
Attempted to create an application using the following settings:

    ? What's the name of your App? adf-example-app
    Your generator must be inside a folder named adf-example-app
    I'll automatically create this folder.
    ? How would you describe the app? Alfresco Angular 2 Application Example
    ? Author's Name Steve Bennett
    ? Author's Email steve@steve.codes
    ? Author's Homepage 
    ? Package keywords (comma to split) 
    ? What is your Alfresco platform server URL? http://localhost:8888
    ? What is your Activiti platform server URL? http://localhost:8888
    ? GitHub username or organization 
    ? Do you want include the User info component? No
    ? Do you want include a drawer bar? No
    ? Do you want include a search bar? Yes
    ? Do you want include a Document List? Yes
    ? Do you want include a Tasks List? No
    ? Which license do you want to use? MIT

Results in the following directories and files being created:

    create app/main.ts
    create app/components/index.ts
    create app/app.routes.ts
    create app/app.module.ts
    create app/app.component.ts
    create app/app.component.html
    create app/app.component.css
    create app/components/login/login-demo.component.ts
    create app/components/login/login-demo.component.html
    create app/components/login/login-demo.component.css
    create assets/material.orange-blue.min.css
    create app/css/muli-font.css
    create app/css/app.css
    create app/fonts/Muli-Regular.ttf
    create i18n/en.json
    create i18n/it.json
    create app/components/search/search.component.html
    create app/components/search/search.component.ts
    create app/components/search/search-bar.component.ts
    create app/components/search/search-bar.component.html
    create app/components/files/files.component.html
    create app/components/files/files.component.css
    create app/components/files/files.component.ts
    create typings.json
    create tslint.json
    create tsconfig.json
    create systemjs.config.js
    create angular-cli.json
    create README.md
    create index.html
    create .gitignore
    create .editorconfig
    create package.json
    create LICENSE

`npm install` then completes successfully, but `npm start` fails due to missing `setting.component`. Full logs attached.

[adf-example-start.txt](https://github.com/Alfresco/generator-ng2-alfresco-app/files/655166/adf-example-start.txt)

**Comment by magemello** [comment]
fix in 1.0.0
