### ISSUE TITLE
npm run start fails on mac machine bug

### ISSUE THREAD

**Issue by kodermax** [Alfresco/generator-ng2-alfresco-app#59]
![image](https://cloud.githubusercontent.com/assets/590985/22407288/c407b66c-e674-11e6-8cd0-cbe1b140d913.png)

**Comment by eromano** [comment]
Hi @kodermax can you try to cahnge in the  package.json ``` "alfresco-js-api": "^1.0.0" ``` with ``` "alfresco-js-api": "1.0.0" ``` and run the command ```npm update``` ?

**Comment by kodermax** [comment]
Thank you.
It works.
