### ISSUE TITLE
npm run build doens't work

### ISSUE THREAD

**Issue by magemello** [Alfresco/generator-ng2-alfresco-app#61]
The javascript api is not build by the UglifyJsPlugin of webpack. UglifyJsPlugin doesn't support ES6.

**Workaround:**

Edit **config/webpack.prod.js** and comment the following lines:

```
new webpack.optimize.UglifyJsPlugin({
      mangle: {
        keep_fnames: true
      },
      compressor: {
        screw_ie8: true,
        warnings: false
      }
    }),
```

**Comment by DenisVuyka** [comment]
`alfresco-js-api` must be pointing to the bundle within it's `package.json` file, now it's pointing to source code that is ES6.
