### ISSUE TITLE
Add in support for app upgrades

### ISSUE THREAD

**Issue by davidcognite** [Alfresco/generator-ng2-alfresco-app#62]
Feature Request.

As an app developer
I would like to run a simple command to update my app
To allow me to use new features and get bug fixes quickly.

Note: This is similar to features offered in the Angular CLI.

**Comment by eromano** [comment]
Hi, @davidcognite how should behave this upgrade with the customization did from the user?
At the moment if you run the generator in the same folder where you already have an old project yeoman will ask you if you want to overwrite the file or not. In this way, you can choose which file update and which not.

**Comment by DenisVuyka** [comment]
Closing as it has no relation to the main purpose of the scaffold generation.
