### ISSUE TITLE
Syntax error if you try to run created ADF 1.1 project with "npm start"

### ISSUE THREAD

**Issue by mmuller88** [Alfresco/generator-ng2-alfresco-app#63]
When you follow the steps on https://ts.alfresco.com/share/s/9iu7Phg0QrezPj6JJAdstQ it can produce a SyntaxError.
My assumption is because I'm using OSX.

Environment:
- mac laptop with OSX El Capitan 10.11.6. Engineer version like 512GB Storage 16GB RAM
- npm 4.0.5, node v5.7.1

Steps:
1) Follow the instruction in section 2.3 https://ts.alfresco.com/share/s/9iu7Phg0QrezPj6JJAdstQ
  - Open a terminal and move to a folder where you want to create your project
  - yo ng2-alfresco-app
  - I used this settings with the wizard
  ? What's the name of your App? dia-trace-2
  ? How would you describe the app? Activity Recognition
  ? Author's Name Martin Muller
  ? Author's Email martin.muller@alfresco.com
  ? Author's Homepage 
  ? Package keywords (comma to split) 
  ? What is your Alfresco platform server URL? http://127.0.0.1:8080
  ? What is your Activiti platform server URL? http://127.0.0.1:9999
  ? GitHub username or organization mmuller88
  ? Do you want include the User info component? Yes
  ? Do you want include a drawer bar? Yes
  ? Do you want include a search bar? Yes
  ? Do you want include a Document List? Yes
  ? Do you want include Activiti BPM components? No
  ? Which license do you want to use? Apache 2.0
2) Start the app
  - Open a terminal and move to the folder representing your brand new application (in this example dia-trace-2)
  - npm install
  - npm start

Expected result:
  - Starting the ADF app without an error
  
Actual result:
  - Not starting the ADF app. Syntax error is shown
  
Log:
/Users/mmuller/Documents/ADF/proj1/dia-trace2/dia-trace-2/config/webpack.common.js:12
let pattern = '+(alfresco-js-api|ng2-alfresco|ng2-activiti)*';
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/mmuller/Documents/ADF/proj1/dia-trace2/dia-trace-2/config/webpack.dev.js:3:20)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
  
Notice:
You can fix the error manually if you go to the JS file and change the keyword "let" to "var"

**Comment by eromano** [comment]
Hi @mmuller88 wich version of npm and nodejs do you have?

```
npm -v
node -v
```

**Comment by mmuller88** [comment]
- npm 4.0.5, node v5.7.1

**Comment by eromano** [comment]
Thanks @mmuller88  that seems to be an issue on the version 5 of node if you update to the version  you will not  have this problem.
We will fix this on the next version thanks to report it

**Comment by mmuller88** [comment]
Jup that fixed it. It seems I had several node versions one from brew and an other one. I thought my running node is up to date. I only use now only that from brew :). Thanks
