### ISSUE TITLE
UI does not fallback to english if native browser locale is not available. many labels missing

### ISSUE THREAD

**Issue by romainguinot** [Alfresco/generator-ng2-alfresco-app#64]
Hi, 

If you have a browser with a non-english locale, many (if not all) labels are missing. 
You need a browser with just english. 

There needs to be a fallback to english if the native language is not available. 
Ideally, go through the browser's accept languages to see if there is a potential match, and, if not, fallback to english. 

See attached screenshots. 

![process](https://cloud.githubusercontent.com/assets/1854212/22700581/7298cb34-ed5b-11e6-807a-1bd0e98ac50b.png)
![login](https://cloud.githubusercontent.com/assets/1854212/22700582/729a158e-ed5b-11e6-8c57-1fd3d3b90f5b.png)
![doclist](https://cloud.githubusercontent.com/assets/1854212/22700584/72a2eefc-ed5b-11e6-9e3c-6514d3889cc9.png)

**Comment by eromano** [comment]
Hi @romainguinot this repo is only the generator for the scaffolding of an ADF application.
If you want propose an enhancement or an issue to the ADF project the right repository is https://github.com/Alfresco/alfresco-ng2-components.
Thanks
