### ISSUE TITLE
Hangs on the second question.

### ISSUE THREAD

**Issue by magp3** [Alfresco/generator-ng2-alfresco-app#87]
When running
yo ng2-alfresco-app
it asks "How would you describe the app? (Alfresco Angular 2 Application Example)"
and no matter what I do I can't get past this step.

`DEBUG=yeoman:generator yo ng2-alfresco-app
? What's the name of your App? test
  yeoman:generator Running default +1s
Your generator must be inside a folder named test
I'll automatically create this folder.
  yeoman:generator Running askFor +5ms
? How would you describe the app? (Alfresco Angular 2DEBUG=yeoman:generator yo ng2-alfresco-app
 Application Example)`

Using:
node: 8.1.0
npm:5.0.3
yo: 1.8.5 (tried 2.0.0 with the same issues)

**Comment by eromano** [comment]
@magp3 can you try to use node 7?
