### ISSUE TITLE
`npm run start:dev` fails

### ISSUE THREAD

**Issue by IgorZh** [Alfresco/generator-ng2-alfresco-app#97]
Hi.
I generated new project, run `npm i` then `npm start` all works fine.
When I run `npm run start:dev` I get list of errors like this
```
ERROR in ./app/vendor.ts
Module not found: Error: Can't resolve 'ng2-activiti-analytics' in '/Users/izheleznov/projects/panda/app'
 @ ./app/vendor.ts 12:0-33
 @ multi (webpack)-dev-server/client?http://0.0.0.0:3000 ./app/vendor.ts
```

**Comment by eromano** [comment]
you need to use npm run start , npm run start:dev woks only if you have next your generated project the https://github.com/Alfresco/alfresco-ng2-components/tree/master/ng2-components folder
